-- =================================================================
-- SCRIPT DE MIGRACAO DO PROJETO CARLO ACUTIS PARA SUPABASE
-- Cole este script no SQL Editor do seu Dashboard Supabase e execute.
-- Este script é IDEMPOTENTE: pode ser rodado mais de uma vez sem erro.
-- =================================================================

-- Enable UUID Extension if not enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. TABELA DE LIGAS PAROQUIAIS
CREATE TABLE IF NOT EXISTS public.ligas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    codigo_acesso VARCHAR(20) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. TABELA DE PROFILES (ESTENDE AUTH.USERS)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    xp INT NOT NULL DEFAULT 0,
    nivel VARCHAR(100) NOT NULL DEFAULT 'Peregrino',
    liga_id BIGINT REFERENCES public.ligas(id) ON DELETE SET NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. TABELA DE TEMPORADAS DO QUIZ
--    GENERATED BY DEFAULT permite forçar IDs fixos no seed data,
--    garantindo a idempotência real do ON CONFLICT (id) DO NOTHING.
CREATE TABLE IF NOT EXISTS public.temporadas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    descricao TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. TABELA DE PERGUNTAS DO QUIZ
--    CHAR(1) em resposta_correta: valor sempre será 'A','B','C' ou 'D'.
--    Mais preciso e eficiente que VARCHAR(5).
--    GENERATED BY DEFAULT para permitir IDs fixos no seed data.
CREATE TABLE IF NOT EXISTS public.perguntas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    temporada_id BIGINT NOT NULL REFERENCES public.temporadas(id) ON DELETE CASCADE,
    texto_pergunta TEXT NOT NULL,
    opcao_a TEXT NOT NULL,
    opcao_b TEXT NOT NULL,
    opcao_c TEXT NOT NULL,
    opcao_d TEXT NOT NULL,
    resposta_correta CHAR(1) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. TABELA DE HISTORICO DE RESPOSTAS DO USUARIO (EVITA XP REPETIDO)
CREATE TABLE IF NOT EXISTS public.respostas_usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    pergunta_id BIGINT NOT NULL REFERENCES public.perguntas(id) ON DELETE CASCADE,
    acertou BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_user_pergunta UNIQUE (user_id, pergunta_id)
);

-- =================================================================
-- CORRECAO DE COLUNAS IDENTITY EM TABELAS JA EXISTENTES
-- -----------------------------------------------------------------
-- Se as tabelas já existiam com GENERATED ALWAYS, o CREATE TABLE IF NOT
-- EXISTS acima não as recria. Os comandos abaixo garantem que todas as
-- colunas identity usem BY DEFAULT, permitindo IDs explícitos no seed.
-- =================================================================
ALTER TABLE IF EXISTS public.ligas              ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE IF EXISTS public.temporadas         ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE IF EXISTS public.perguntas          ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE IF EXISTS public.respostas_usuario  ALTER COLUMN id SET GENERATED BY DEFAULT;

-- =================================================================
-- INDICES DE PERFORMANCE EM CHAVES ESTRANGEIRAS
-- -----------------------------------------------------------------
-- O PostgreSQL NÃO cria índices automaticamente em FKs.
-- Sem esses índices, JOINs e filtros por liga/temporada fazem
-- varreduras sequenciais (seq scan), ficando muito lentos com volume.
-- =================================================================

-- Melhora performance ao filtrar profiles por liga (ranking da liga, etc.)
CREATE INDEX IF NOT EXISTS idx_profiles_liga_id ON public.profiles(liga_id);

-- Melhora performance ao buscar perguntas de uma temporada específica
CREATE INDEX IF NOT EXISTS idx_perguntas_temporada_id ON public.perguntas(temporada_id);

-- Melhora performance ao buscar histórico de respostas de um usuário
-- (complementa a UNIQUE constraint que já cobre buscas por user_id + pergunta_id)
CREATE INDEX IF NOT EXISTS idx_respostas_user_id ON public.respostas_usuario(user_id);

-- =================================================================
-- TRIGGER PARA CRIAR PROFILE AUTOMATICAMENTE QUANDO UM USUARIO SE REGISTRA
-- =================================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, nome, email, xp, nivel)
    VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data->>'nome', 'Peregrino'),
        NEW.email,
        0,
        'Peregrino'
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop trigger if exists to prevent duplication
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- =================================================================
-- FUNCTION RPC PARA CALCULAR TITULO / NIVEL BASEADO NO XP
-- =================================================================
CREATE OR REPLACE FUNCTION public.calcular_titulo(xp_total INT)
RETURNS VARCHAR AS $$
DECLARE
    nivel_num INT;
BEGIN
    nivel_num := (xp_total / 1000) + 1;
    IF nivel_num < 5 THEN
        RETURN 'Peregrino';
    ELSIF nivel_num < 10 THEN
        RETURN 'Discípulo';
    ELSIF nivel_num < 20 THEN
        RETURN 'Missionário';
    ELSIF nivel_num < 50 THEN
        RETURN 'Apóstolo Digital';
    ELSE
        RETURN 'Ciberapóstolo da Eucaristia';
    END IF;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- =================================================================
-- FUNCTION RPC PARA RESPONDER PERGUNTA COM SEGURANCA NO BANCO
-- -----------------------------------------------------------------
-- Esta função roda como SECURITY DEFINER (com permissões de admin),
-- portanto o usuário nunca precisa de acesso direto de UPDATE em xp/nivel.
-- O parâmetro é CHAR(1) pois a resposta sempre será 'A', 'B', 'C' ou 'D'.
-- =================================================================
CREATE OR REPLACE FUNCTION public.responder_pergunta(
    p_pergunta_id BIGINT,
    p_resposta_selecionada CHAR(1)
)
RETURNS JSONB AS $$
DECLARE
    v_user_id UUID;
    v_resposta_correta CHAR(1);
    v_is_correct BOOLEAN := FALSE;
    v_ja_respondida BOOLEAN := FALSE;
    v_new_xp INT;
    v_new_nivel VARCHAR;
BEGIN
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Usuário não autenticado.';
    END IF;

    SELECT resposta_correta INTO v_resposta_correta
    FROM public.perguntas
    WHERE id = p_pergunta_id;

    IF v_resposta_correta IS NULL THEN
        RAISE EXCEPTION 'Pergunta não encontrada.';
    END IF;

    -- Verifica se o usuário já respondeu a esta pergunta antes
    SELECT EXISTS (
        SELECT 1
        FROM public.respostas_usuario
        WHERE user_id = v_user_id
          AND pergunta_id = p_pergunta_id
    ) INTO v_ja_respondida;

    IF UPPER(v_resposta_correta) = UPPER(p_resposta_selecionada) THEN
        v_is_correct := TRUE;
    END IF;

    IF NOT v_ja_respondida THEN
        -- Registra a resposta no histórico do usuário
        INSERT INTO public.respostas_usuario (user_id, pergunta_id, acertou)
        VALUES (v_user_id, p_pergunta_id, v_is_correct);

        -- Concede XP apenas se for a primeira vez e a resposta for correta
        IF v_is_correct THEN
            UPDATE public.profiles
            SET xp = xp + 100,
                nivel = public.calcular_titulo(xp + 100),
                updated_at = NOW()
            WHERE id = v_user_id
            RETURNING xp, nivel INTO v_new_xp, v_new_nivel;
        ELSE
            SELECT xp, nivel INTO v_new_xp, v_new_nivel
            FROM public.profiles
            WHERE id = v_user_id;
        END IF;
    ELSE
        -- Usuário já respondeu anteriormente (não soma XP novamente)
        SELECT xp, nivel INTO v_new_xp, v_new_nivel
        FROM public.profiles
        WHERE id = v_user_id;
    END IF;

    RETURN jsonb_build_object(
        'correct', v_is_correct,
        'xp', v_new_xp,
        'nivel', v_new_nivel,
        'first_attempt', NOT v_ja_respondida
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =================================================================
-- FUNCTION RPC PARA CRIAR UMA LIGA PAROQUIAL COM SEGURANÇA
-- -----------------------------------------------------------------
-- Roda como SECURITY DEFINER para poder atualizar liga_id em profiles
-- sem expor permissão de UPDATE direta ao usuário.
-- =================================================================
CREATE OR REPLACE FUNCTION public.criar_liga(p_nome TEXT)
RETURNS JSONB AS $$
DECLARE
    v_user_id UUID;
    v_codigo TEXT;
    v_nova_liga_id BIGINT;
    v_liga_nome VARCHAR;
    v_liga_codigo VARCHAR;
BEGIN
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Usuário não autenticado.';
    END IF;

    IF TRIM(p_nome) = '' THEN
        RAISE EXCEPTION 'Nome da liga não pode ser vazio.';
    END IF;

    -- Gera código de acesso único de 8 caracteres alfanuméricos (maiúsculos)
    v_codigo := UPPER(SUBSTRING(MD5(RANDOM()::TEXT || CLOCK_TIMESTAMP()::TEXT) FROM 1 FOR 8));

    INSERT INTO public.ligas (nome, codigo_acesso)
    VALUES (TRIM(p_nome), v_codigo)
    RETURNING id, nome, codigo_acesso INTO v_nova_liga_id, v_liga_nome, v_liga_codigo;

    -- Vincula o usuário à nova liga de forma segura (sem UPDATE direto no front)
    UPDATE public.profiles
    SET liga_id = v_nova_liga_id,
        updated_at = NOW()
    WHERE id = v_user_id;

    RETURN jsonb_build_object(
        'liga_id', v_nova_liga_id,
        'nome', v_liga_nome,
        'codigo_acesso', v_liga_codigo
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =================================================================
-- FUNCTION RPC PARA ENTRAR EM UMA LIGA PAROQUIAL COM SEGURANÇA
-- -----------------------------------------------------------------
-- Roda como SECURITY DEFINER para poder atualizar liga_id em profiles
-- sem expor permissão de UPDATE direta ao usuário.
-- =================================================================
CREATE OR REPLACE FUNCTION public.entrar_liga(p_codigo TEXT)
RETURNS JSONB AS $$
DECLARE
    v_user_id UUID;
    v_liga_id BIGINT;
    v_liga_nome VARCHAR;
    v_liga_codigo VARCHAR;
BEGIN
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Usuário não autenticado.';
    END IF;

    -- Busca liga pelo código (case-insensitive via UPPER)
    SELECT id, nome, codigo_acesso INTO v_liga_id, v_liga_nome, v_liga_codigo
    FROM public.ligas
    WHERE UPPER(codigo_acesso) = UPPER(TRIM(p_codigo));

    IF v_liga_id IS NULL THEN
        RAISE EXCEPTION 'Código de liga inválido ou não encontrado.';
    END IF;

    -- Vincula o usuário à liga de forma segura (sem UPDATE direto no front)
    UPDATE public.profiles
    SET liga_id = v_liga_id,
        updated_at = NOW()
    WHERE id = v_user_id;

    RETURN jsonb_build_object(
        'liga_id', v_liga_id,
        'nome', v_liga_nome,
        'codigo_acesso', v_liga_codigo
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =================================================================
-- FUNCTION RPC PARA SAIR DE UMA LIGA PAROQUIAL COM SEGURANÇA
-- -----------------------------------------------------------------
-- Permite que o usuário deixe a liga atual definindo liga_id como NULL.
-- =================================================================
CREATE OR REPLACE FUNCTION public.sair_liga()
RETURNS JSONB AS $$
DECLARE
    v_user_id UUID;
BEGIN
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Usuário não autenticado.';
    END IF;

    -- Desvincula o usuário da liga (seta NULL)
    UPDATE public.profiles
    SET liga_id = NULL,
        updated_at = NOW()
    WHERE id = v_user_id;

    RETURN jsonb_build_object('success', true);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =================================================================
-- CONFIGURACAO DE ROW LEVEL SECURITY (RLS)
-- =================================================================
ALTER TABLE public.ligas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.temporadas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.perguntas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.respostas_usuario ENABLE ROW LEVEL SECURITY;

-- As policies usam DROP POLICY IF EXISTS antes de cada CREATE POLICY
-- para que este script possa ser executado várias vezes sem erro
-- de "policy already exists".

-- Policies para Respostas Usuario
DROP POLICY IF EXISTS "Leitura de Respostas pelo próprio usuário" ON public.respostas_usuario;
CREATE POLICY "Leitura de Respostas pelo próprio usuário"
    ON public.respostas_usuario FOR SELECT
    TO authenticated USING (auth.uid() = user_id);

-- Policies para Ligas
DROP POLICY IF EXISTS "Leitura de Ligas permitida para autenticados" ON public.ligas;
CREATE POLICY "Leitura de Ligas permitida para autenticados"
    ON public.ligas FOR SELECT
    TO authenticated USING (true);

DROP POLICY IF EXISTS "Criação de Ligas permitida para autenticados" ON public.ligas;
CREATE POLICY "Criação de Ligas permitida para autenticados"
    ON public.ligas FOR INSERT
    TO authenticated WITH CHECK (true);

-- Policies para Profiles
DROP POLICY IF EXISTS "Leitura de Profiles permitida para autenticados" ON public.profiles;
CREATE POLICY "Leitura de Profiles permitida para autenticados"
    ON public.profiles FOR SELECT
    TO authenticated USING (true);

-- UPDATE restrito: apenas a coluna `nome` é atualizável diretamente.
-- Colunas `xp`, `nivel` e `liga_id` são somente alteráveis via RPCs com
-- SECURITY DEFINER (responder_pergunta, criar_liga, entrar_liga).
DROP POLICY IF EXISTS "Atualização de Profile pelo próprio usuário" ON public.profiles;
CREATE POLICY "Atualização de Profile pelo próprio usuário"
    ON public.profiles FOR UPDATE
    TO authenticated USING (auth.uid() = id);

-- INSERT em profiles é necessário apenas pela trigger handle_new_user
-- (SECURITY DEFINER), mas a policy precisa existir.
DROP POLICY IF EXISTS "Inserção de Profile pelo sistema" ON public.profiles;
CREATE POLICY "Inserção de Profile pelo sistema"
    ON public.profiles FOR INSERT
    TO authenticated WITH CHECK (auth.uid() = id);

-- Policies para Temporadas
DROP POLICY IF EXISTS "Leitura de Temporadas pública" ON public.temporadas;
CREATE POLICY "Leitura de Temporadas pública"
    ON public.temporadas FOR SELECT
    TO anon, authenticated USING (true);

-- Policies para Perguntas
DROP POLICY IF EXISTS "Leitura de Perguntas pública" ON public.perguntas;
CREATE POLICY "Leitura de Perguntas pública"
    ON public.perguntas FOR SELECT
    TO anon, authenticated USING (true);

-- =================================================================
-- GRANTS DE PRIVILÉGIO NAS TABELAS (NECESSÁRIO ALÉM DA RLS!)
-- -----------------------------------------------------------------
-- O RLS filtra QUAIS LINHAS um role pode ver/alterar, mas antes disso
-- o Postgres exige que o role tenha o GRANT básico na tabela. Sem essas
-- linhas abaixo, mesmo com as policies certas, o PostgREST retorna
-- erro 403 (permission denied) em vez de aplicar a policy.
-- =================================================================
GRANT SELECT ON public.profiles TO authenticated;

-- SEGURANÇA: Revoga UPDATE geral da tabela profiles.
-- Apenas a coluna `nome` pode ser atualizada diretamente pelo usuário.
-- Colunas `xp`, `nivel` e `liga_id` são gerenciadas exclusivamente
-- pelas RPCs com SECURITY DEFINER (responder_pergunta, criar_liga, entrar_liga).
REVOKE UPDATE ON public.profiles FROM authenticated;
GRANT UPDATE (nome) ON public.profiles TO authenticated;

GRANT SELECT, INSERT ON public.ligas TO authenticated;
GRANT SELECT ON public.temporadas TO anon, authenticated;
GRANT SELECT ON public.perguntas TO anon, authenticated;
GRANT SELECT ON public.respostas_usuario TO authenticated;

-- Garante acesso às sequences por trás dos IDs GENERATED AS IDENTITY
-- (necessário para os INSERTs liberados por policy, ex: criação de ligas)
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- Garante que tabelas criadas no futuro já herdem essas permissões
-- automaticamente, evitando repetir esse problema depois
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT ON TABLES TO anon;

-- =================================================================
-- SEED DATA (DADOS INICIAIS DE TESTE)
-- -----------------------------------------------------------------
-- IDs são fixos (1, 2...) para que ON CONFLICT (id) DO NOTHING funcione
-- corretamente e este script seja verdadeiramente idempotente.
-- O uso de GENERATED BY DEFAULT nas tabelas permite forçar esses IDs.
-- =================================================================
INSERT INTO public.temporadas (id, titulo, descricao)
VALUES
    (1, 'Temporada 1: Vida e Eucaristia',
        'Conheça os primeiros anos e a profunda devoção eucarística de Carlo Acutis.'),
    (2, 'Temporada 2: Milagres Eucarísticos e Tecnologia',
        'Descubra como Carlo usou a computação para evangelizar o mundo.'),
    (3, 'Temporada 3: A Paixão pela Internet e Ação Social',
        'Explore como ele uniu suas habilidades tecnológicas com o amor aos mais pobres.'),
    (4, 'Temporada 4: Doença, Partida e Beatificação',
        'Acompanhe os últimos dias de Carlo, sua oferta a Deus e o caminho para os altares.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.perguntas (id, temporada_id, texto_pergunta, opcao_a, opcao_b, opcao_c, opcao_d, resposta_correta)
VALUES
    -- TEMPORADA 1 (IDs 1-5)
    (1, 1, 'Em qual cidade Carlo Acutis nasceu?',
        'Milão', 'Londres', 'Roma', 'Assis', 'B'),
    (2, 1, 'Qual expressão famosa Carlo Acutis dizia sobre a Eucaristia?',
        'Meu plano de vida', 'Minha autoestrada para o céu', 'Meu refúgio diário', 'Minha luz divina', 'B'),
    (3, 1, 'Com quantos anos Carlo Acutis fez sua Primeira Comunhão (antes do tempo habitual)?',
        '7 anos', '9 anos', '10 anos', '12 anos', 'A'),
    (4, 1, 'Qual era o principal "projeto de vida" de Carlo, segundo suas próprias palavras?',
        'Ser um grande programador', 'Viajar o mundo', 'Estar sempre unido a Jesus', 'Criar uma ONG', 'C'),
    (5, 1, 'Onde Carlo Acutis passava frequentemente as férias e onde pediu para ser sepultado?',
        'Milão', 'Florença', 'Londres', 'Assis', 'D'),

    -- TEMPORADA 2 (IDs 6-10)
    (6, 2, 'O que Carlo Acutis criou na internet para evangelizar?',
        'Um jogo de RPG católico', 'Uma rede social para jovens',
        'Uma exposição virtual dos Milagres Eucarísticos', 'Um aplicativo de orações diárias', 'C'),
    (7, 2, 'Qual destes programas de computador Carlo usava para criar seus projetos evangelizadores?',
        'Photoshop e C++', 'Word e Excel apenas', 'Não usava programas complexos', 'Apenas jogos', 'A'),
    (8, 2, 'Quantos anos ele levou para concluir sua pesquisa sobre os Milagres Eucarísticos para o site?',
        '1 ano', '2 anos e meio', '5 anos', 'Apenas alguns meses', 'B'),
    (9, 2, 'Além dos milagres eucarísticos, qual outro tema religioso ele catalogou online?',
        'Aparições Marianas', 'História dos Papas', 'História de Israel', 'Vidas dos mártires romanos', 'A'),
    (10, 2, 'Qual animal de estimação Carlo gostava muito de cuidar em casa?',
        'Cães e gatos', 'Pássaros', 'Peixes', 'Coelhos', 'A'),

    -- TEMPORADA 3 (IDs 11-15)
    (11, 3, 'O que Carlo costumava fazer com a sua "mesada" (dinheiro extra)?',
        'Comprava jogos de videogame', 'Poupava para comprar equipamentos', 'Dava para pessoas em situação de rua', 'Gastava em doces', 'C'),
    (12, 3, 'Qual era a atitude de Carlo quando encontrava colegas sofrendo bullying na escola?',
        'Ele ignorava', 'Ele os defendia', 'Ele ria junto', 'Ele mudava de assunto', 'B'),
    (13, 3, 'Quem Carlo ajudou a catequizar e que acabou se convertendo ao catolicismo?',
        'Seu professor de matemática', 'Rajesh, o funcionário hindu de sua casa', 'Seus pais biológicos', 'Um amigo ateu do bairro', 'B'),
    (14, 3, 'Qual destes Santos era um grande modelo para a vida de caridade de Carlo Acutis?',
        'São Tomás de Aquino', 'São João Paulo II', 'São Francisco de Assis', 'Santo Agostinho', 'C'),
    (15, 3, 'Como os colegas de Carlo o descreviam no ambiente escolar?',
        'Isolado e calado', 'Nerd e antipático', 'Alegre, prestativo e amigável', 'Competitivo e focado apenas nos estudos', 'C'),

    -- TEMPORADA 4 (IDs 16-20)
    (16, 4, 'Qual foi a grave doença diagnosticada em Carlo Acutis pouco antes de sua morte?',
        'Câncer no pulmão', 'Leucemia fulminante', 'Tuberculose', 'Pneumonia grave', 'B'),
    (17, 4, 'A quem Carlo ofereceu os sofrimentos de sua doença?',
        'À sua família', 'Ao Papa e à Igreja', 'Aos pobres de Assis', 'Aos seus amigos', 'B'),
    (18, 4, 'Em que data Carlo Acutis faleceu?',
        '12 de outubro de 2006', '10 de novembro de 2006', '25 de dezembro de 2005', '15 de agosto de 2007', 'A'),
    (19, 4, 'O milagre que levou à beatificação de Carlo Acutis aconteceu em qual país?',
        'Brasil (Mato Grosso do Sul)', 'Itália', 'Estados Unidos', 'Argentina', 'A'),
    (20, 4, 'Em que ano Carlo Acutis foi oficialmente beatificado pela Igreja Católica?',
        '2018', '2019', '2020', '2021', 'C')
ON CONFLICT (id) DO NOTHING;
-- =================================================================
-- =================================================================
-- ATUALIZAÇÃO — AUDITORIA DE 29/08/2026
-- -----------------------------------------------------------------
-- Este bloco é aditivo e idempotente: pode ser colado e executado
-- no SQL Editor do Supabase mesmo em um banco que já rodou a versão
-- anterior deste script. Cobre:
--   1) Correções de integridade (nivel gerado, sync de e-mail)
--   2) Papel de admin + controle de conteúdo (temporadas/perguntas)
--   3) Gamificação (streak diário + conquistas)
--   4) Limite de criação de ligas e validações extras nas RPCs
-- =================================================================
-- =================================================================


-- =================================================================
-- 1. CORREÇÃO: "nivel" deixa de ser gravado manualmente e passa a
--    ser uma COLUNA GERADA a partir do xp. Isso elimina de vez o
--    risco de "nivel" ficar desatualizado em relação ao xp (drift),
--    caso as faixas de calcular_titulo mudem no futuro.
-- =================================================================
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'profiles'
          AND column_name = 'nivel' AND is_generated = 'NEVER'
    ) THEN
        ALTER TABLE public.profiles DROP COLUMN nivel;
        ALTER TABLE public.profiles
            ADD COLUMN nivel VARCHAR(100) GENERATED ALWAYS AS (public.calcular_titulo(xp)) STORED;
    END IF;
END $$;

-- =================================================================
-- 2. CORREÇÃO: sincroniza profiles.email quando o e-mail é alterado
--    em auth.users (hoje só era copiado na criação da conta).
-- =================================================================
CREATE OR REPLACE FUNCTION public.handle_user_updated()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.email IS DISTINCT FROM OLD.email THEN
        UPDATE public.profiles
        SET email = NEW.email, updated_at = NOW()
        WHERE id = NEW.id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_updated ON auth.users;
CREATE TRIGGER on_auth_user_updated
    AFTER UPDATE ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_user_updated();

-- Ajusta a trigger de criação de usuário: "nivel" não é mais inserido
-- manualmente (agora é coluna gerada).
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, nome, email, xp)
    VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data->>'nome', 'Peregrino'),
        NEW.email,
        0
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- =================================================================
-- 3. PAPEL DE ADMINISTRADOR
-- -----------------------------------------------------------------
-- Permite designar usuários como admin (via
-- UPDATE public.profiles SET role = 'admin' WHERE email = '...';)
-- para gerenciar temporadas/perguntas sem precisar editar SQL.
-- =================================================================
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS role VARCHAR(20) NOT NULL DEFAULT 'user';

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'profiles_role_check') THEN
        ALTER TABLE public.profiles ADD CONSTRAINT profiles_role_check CHECK (role IN ('user', 'admin'));
    END IF;
END $$;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
    SELECT EXISTS (
        SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'
    );
$$ LANGUAGE sql SECURITY DEFINER STABLE;

-- =================================================================
-- 4. CONTROLE DE CONTEÚDO: ordem/ativação de temporadas e perguntas
-- -----------------------------------------------------------------
-- Permite organizar sessões (ativar/desativar, reordenar) sem
-- precisar de deploy ou SQL manual — feito pela tela /admin.
-- =================================================================
ALTER TABLE public.temporadas ADD COLUMN IF NOT EXISTS ordem INT;
ALTER TABLE public.temporadas ADD COLUMN IF NOT EXISTS ativa BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE public.perguntas  ADD COLUMN IF NOT EXISTS ordem INT;

-- Backfill: usa o próprio id como ordem para linhas já existentes,
-- preservando o comportamento atual.
UPDATE public.temporadas SET ordem = id WHERE ordem IS NULL;
UPDATE public.perguntas  SET ordem = id WHERE ordem IS NULL;

CREATE INDEX IF NOT EXISTS idx_temporadas_ordem ON public.temporadas(ordem);
CREATE INDEX IF NOT EXISTS idx_perguntas_ordem ON public.perguntas(temporada_id, ordem);

-- Policies de escrita para admin em temporadas e perguntas.
-- (A leitura pública já existe e continua liberada via as policies
-- "Leitura de Temporadas pública" / "Leitura de Perguntas pública".)
DROP POLICY IF EXISTS "Admin gerencia Temporadas" ON public.temporadas;
CREATE POLICY "Admin gerencia Temporadas"
    ON public.temporadas FOR ALL
    TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Admin gerencia Perguntas" ON public.perguntas;
CREATE POLICY "Admin gerencia Perguntas"
    ON public.perguntas FOR ALL
    TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

GRANT INSERT, UPDATE, DELETE ON public.temporadas TO authenticated;
GRANT INSERT, UPDATE, DELETE ON public.perguntas TO authenticated;


-- =================================================================
-- 5. GAMIFICAÇÃO: SEQUÊNCIA DIÁRIA (STREAK)
-- =================================================================
CREATE TABLE IF NOT EXISTS public.streaks (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    streak_atual INT NOT NULL DEFAULT 0,
    maior_streak INT NOT NULL DEFAULT 0,
    ultimo_acesso DATE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.streaks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Leitura de Streak pelo próprio usuário" ON public.streaks;
CREATE POLICY "Leitura de Streak pelo próprio usuário"
    ON public.streaks FOR SELECT
    TO authenticated USING (auth.uid() = user_id);

GRANT SELECT ON public.streaks TO authenticated;

-- =================================================================
-- 6. GAMIFICAÇÃO: CONQUISTAS (BADGES)
-- =================================================================
CREATE TABLE IF NOT EXISTS public.conquistas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    nome VARCHAR(255) NOT NULL,
    descricao TEXT,
    icone VARCHAR(10) NOT NULL DEFAULT '🏅',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.usuario_conquistas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    conquista_id BIGINT NOT NULL REFERENCES public.conquistas(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_user_conquista UNIQUE (user_id, conquista_id)
);

CREATE INDEX IF NOT EXISTS idx_usuario_conquistas_user_id ON public.usuario_conquistas(user_id);

ALTER TABLE public.conquistas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usuario_conquistas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Leitura pública de Conquistas" ON public.conquistas;
CREATE POLICY "Leitura pública de Conquistas"
    ON public.conquistas FOR SELECT
    TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Leitura de Conquistas de Usuários" ON public.usuario_conquistas;
CREATE POLICY "Leitura de Conquistas de Usuários"
    ON public.usuario_conquistas FOR SELECT
    TO authenticated USING (true);

GRANT SELECT ON public.conquistas TO anon, authenticated;
GRANT SELECT ON public.usuario_conquistas TO authenticated;

-- Helper interno: concede uma conquista uma única vez (idempotente).
CREATE OR REPLACE FUNCTION public.conceder_conquista(p_user_id UUID, p_codigo VARCHAR)
RETURNS VOID AS $$
DECLARE
    v_conquista_id BIGINT;
BEGIN
    SELECT id INTO v_conquista_id FROM public.conquistas WHERE codigo = p_codigo;
    IF v_conquista_id IS NOT NULL THEN
        INSERT INTO public.usuario_conquistas (user_id, conquista_id)
        VALUES (p_user_id, v_conquista_id)
        ON CONFLICT (user_id, conquista_id) DO NOTHING;
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- RPC chamada no login/abertura do app para atualizar a sequência diária.
CREATE OR REPLACE FUNCTION public.registrar_acesso()
RETURNS JSONB AS $$
DECLARE
    v_user_id UUID;
    v_hoje DATE := (timezone('utc'::text, now()))::date;
    v_ultimo DATE;
    v_atual INT;
    v_maior INT;
BEGIN
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Usuário não autenticado.';
    END IF;

    INSERT INTO public.streaks (user_id, streak_atual, maior_streak, ultimo_acesso)
    VALUES (v_user_id, 1, 1, v_hoje)
    ON CONFLICT (user_id) DO NOTHING;

    SELECT ultimo_acesso, streak_atual, maior_streak INTO v_ultimo, v_atual, v_maior
    FROM public.streaks WHERE user_id = v_user_id;

    IF v_ultimo = v_hoje THEN
        -- já registrado hoje, não faz nada
        NULL;
    ELSIF v_ultimo = v_hoje - 1 THEN
        v_atual := v_atual + 1;
        v_maior := GREATEST(v_maior, v_atual);
        UPDATE public.streaks
        SET streak_atual = v_atual, maior_streak = v_maior, ultimo_acesso = v_hoje, updated_at = NOW()
        WHERE user_id = v_user_id;
    ELSE
        v_atual := 1;
        v_maior := GREATEST(v_maior, 1);
        UPDATE public.streaks
        SET streak_atual = 1, maior_streak = v_maior, ultimo_acesso = v_hoje, updated_at = NOW()
        WHERE user_id = v_user_id;
    END IF;

    IF v_atual >= 7 THEN
        PERFORM public.conceder_conquista(v_user_id, 'sequencia_7_dias');
    END IF;

    RETURN jsonb_build_object('streak_atual', v_atual, 'maior_streak', v_maior);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- =================================================================
-- 7. AJUSTES NAS RPCs EXISTENTES
-- -----------------------------------------------------------------
--   - responder_pergunta: valida a letra recebida, não seta mais
--     "nivel" (coluna gerada), concede conquistas de 1ª resposta e
--     de temporada concluída.
--   - criar_liga: registra criado_por e limita a 3 ligas por usuário.
--   - entrar_liga: concede conquista de "entrou_liga".
-- =================================================================

CREATE OR REPLACE FUNCTION public.responder_pergunta(
    p_pergunta_id BIGINT,
    p_resposta_selecionada CHAR(1)
)
RETURNS JSONB AS $$
DECLARE
    v_user_id UUID;
    v_resposta_correta CHAR(1);
    v_temporada_id BIGINT;
    v_is_correct BOOLEAN := FALSE;
    v_ja_respondida BOOLEAN := FALSE;
    v_new_xp INT;
    v_new_nivel VARCHAR;
    v_total_perguntas INT;
    v_total_respondidas INT;
BEGIN
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Usuário não autenticado.';
    END IF;

    IF UPPER(p_resposta_selecionada) NOT IN ('A', 'B', 'C', 'D') THEN
        RAISE EXCEPTION 'Resposta inválida. Use A, B, C ou D.';
    END IF;

    SELECT resposta_correta, temporada_id INTO v_resposta_correta, v_temporada_id
    FROM public.perguntas
    WHERE id = p_pergunta_id;

    IF v_resposta_correta IS NULL THEN
        RAISE EXCEPTION 'Pergunta não encontrada.';
    END IF;

    -- Verifica se o usuário já respondeu a esta pergunta antes
    SELECT EXISTS (
        SELECT 1
        FROM public.respostas_usuario
        WHERE user_id = v_user_id
          AND pergunta_id = p_pergunta_id
    ) INTO v_ja_respondida;

    IF UPPER(v_resposta_correta) = UPPER(p_resposta_selecionada) THEN
        v_is_correct := TRUE;
    END IF;

    IF NOT v_ja_respondida THEN
        -- Registra a resposta no histórico do usuário
        INSERT INTO public.respostas_usuario (user_id, pergunta_id, acertou)
        VALUES (v_user_id, p_pergunta_id, v_is_correct);

        -- Concede XP apenas se for a primeira vez e a resposta for correta
        IF v_is_correct THEN
            UPDATE public.profiles
            SET xp = xp + 100,
                updated_at = NOW()
            WHERE id = v_user_id
            RETURNING xp, nivel INTO v_new_xp, v_new_nivel;

            PERFORM public.conceder_conquista(v_user_id, 'primeira_resposta');

            -- Verifica se a temporada foi concluída (todas as perguntas respondidas)
            SELECT COUNT(*) INTO v_total_perguntas
            FROM public.perguntas WHERE temporada_id = v_temporada_id;

            SELECT COUNT(*) INTO v_total_respondidas
            FROM public.respostas_usuario ru
            JOIN public.perguntas p ON p.id = ru.pergunta_id
            WHERE ru.user_id = v_user_id AND p.temporada_id = v_temporada_id;

            IF v_total_perguntas > 0 AND v_total_respondidas >= v_total_perguntas THEN
                PERFORM public.conceder_conquista(v_user_id, 'temporada_completa');
            END IF;
        ELSE
            SELECT xp, nivel INTO v_new_xp, v_new_nivel
            FROM public.profiles
            WHERE id = v_user_id;
        END IF;
    ELSE
        -- Usuário já respondeu anteriormente (não soma XP novamente)
        SELECT xp, nivel INTO v_new_xp, v_new_nivel
        FROM public.profiles
        WHERE id = v_user_id;
    END IF;

    RETURN jsonb_build_object(
        'correct', v_is_correct,
        'xp', v_new_xp,
        'nivel', v_new_nivel,
        'first_attempt', NOT v_ja_respondida
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Limite de ligas criadas por usuário (evita spam de ligas duplicadas).
ALTER TABLE public.ligas ADD COLUMN IF NOT EXISTS criado_por UUID REFERENCES auth.users(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_ligas_criado_por ON public.ligas(criado_por);

CREATE OR REPLACE FUNCTION public.criar_liga(p_nome TEXT)
RETURNS JSONB AS $$
DECLARE
    v_user_id UUID;
    v_codigo TEXT;
    v_nova_liga_id BIGINT;
    v_liga_nome VARCHAR;
    v_liga_codigo VARCHAR;
    v_ligas_criadas INT;
BEGIN
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Usuário não autenticado.';
    END IF;

    IF TRIM(p_nome) = '' THEN
        RAISE EXCEPTION 'Nome da liga não pode ser vazio.';
    END IF;

    SELECT COUNT(*) INTO v_ligas_criadas FROM public.ligas WHERE criado_por = v_user_id;
    IF v_ligas_criadas >= 3 THEN
        RAISE EXCEPTION 'Você já atingiu o limite de 3 ligas criadas por usuário.';
    END IF;

    -- Gera código de acesso único de 8 caracteres alfanuméricos (maiúsculos)
    v_codigo := UPPER(SUBSTRING(MD5(RANDOM()::TEXT || CLOCK_TIMESTAMP()::TEXT) FROM 1 FOR 8));

    INSERT INTO public.ligas (nome, codigo_acesso, criado_por)
    VALUES (TRIM(p_nome), v_codigo, v_user_id)
    RETURNING id, nome, codigo_acesso INTO v_nova_liga_id, v_liga_nome, v_liga_codigo;

    -- Vincula o usuário à nova liga de forma segura (sem UPDATE direto no front)
    UPDATE public.profiles
    SET liga_id = v_nova_liga_id,
        updated_at = NOW()
    WHERE id = v_user_id;

    PERFORM public.conceder_conquista(v_user_id, 'fundador_liga');

    RETURN jsonb_build_object(
        'liga_id', v_nova_liga_id,
        'nome', v_liga_nome,
        'codigo_acesso', v_liga_codigo
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.entrar_liga(p_codigo TEXT)
RETURNS JSONB AS $$
DECLARE
    v_user_id UUID;
    v_liga_id BIGINT;
    v_liga_nome VARCHAR;
    v_liga_codigo VARCHAR;
BEGIN
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Usuário não autenticado.';
    END IF;

    -- Busca liga pelo código (case-insensitive via UPPER)
    SELECT id, nome, codigo_acesso INTO v_liga_id, v_liga_nome, v_liga_codigo
    FROM public.ligas
    WHERE UPPER(codigo_acesso) = UPPER(TRIM(p_codigo));

    IF v_liga_id IS NULL THEN
        RAISE EXCEPTION 'Código de liga inválido ou não encontrado.';
    END IF;

    -- Vincula o usuário à liga de forma segura (sem UPDATE direto no front)
    UPDATE public.profiles
    SET liga_id = v_liga_id,
        updated_at = NOW()
    WHERE id = v_user_id;

    PERFORM public.conceder_conquista(v_user_id, 'entrou_liga');

    RETURN jsonb_build_object(
        'liga_id', v_liga_id,
        'nome', v_liga_nome,
        'codigo_acesso', v_liga_codigo
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- =================================================================
-- 8. ÍNDICE PARA RANKING GLOBAL (não só por liga)
-- =================================================================
CREATE INDEX IF NOT EXISTS idx_profiles_xp ON public.profiles(xp DESC);


-- =================================================================
-- 9. SEED: CATÁLOGO DE CONQUISTAS
-- =================================================================
INSERT INTO public.conquistas (id, codigo, nome, descricao, icone)
VALUES
    (1, 'primeira_resposta', 'Primeiro Passo', 'Respondeu sua primeira pergunta corretamente.', '🎯'),
    (2, 'temporada_completa', 'Temporada Concluída', 'Completou todas as perguntas de uma temporada.', '🏆'),
    (3, 'entrou_liga', 'Em Comunidade', 'Entrou em uma Liga Paroquial.', '🤝'),
    (4, 'fundador_liga', 'Fundador', 'Criou uma Liga Paroquial.', '🏛️'),
    (5, 'sequencia_7_dias', 'Fé Constante', 'Acessou o app por 7 dias seguidos.', '🔥')
ON CONFLICT (id) DO NOTHING;

-- =================================================================
-- FIM DA ATUALIZAÇÃO
-- -----------------------------------------------------------------
-- Para tornar um usuário administrador (acesso à tela /admin), rode:
--   UPDATE public.profiles SET role = 'admin' WHERE email = 'seu-email@exemplo.com';
-- =================================================================

-- =================================================================
-- =================================================================
-- ATUALIZAÇÃO 2 — ENDURECIMENTO DE SEGURANÇA (plano de 07/09/2026)
-- -----------------------------------------------------------------
-- Também aditivo e idempotente. Cobre:
--   1) search_path fixo em todas as funções SECURITY DEFINER
--   2) profiles restrito ao próprio dono + view pública de ranking
--   3) usuario_conquistas restrito ao próprio usuário
--   4) ligas: esconde codigo_acesso da leitura direta da tabela
--   5) trava a criação de ligas fora da RPC criar_liga
--   6) constraints de integridade (xp, textos, resposta_correta, ordem)
--   7) RPC não responde perguntas de temporada/pergunta inativa
--   8) tabela de auditoria administrativa (triggers automáticos)
--   9) remove os ALTER DEFAULT PRIVILEGES excessivamente permissivos
-- =================================================================
-- =================================================================


-- =================================================================
-- 1. search_path FIXO EM TODAS AS FUNÇÕES SECURITY DEFINER
-- -----------------------------------------------------------------
-- Sem isso, uma role capaz de criar objetos em algum schema que apareça
-- antes de "public" no search_path do executor poderia, em teoria,
-- "sequestrar" a resolução de nomes dentro da função (search_path
-- hijacking). Fixamos explicitamente para blindar isso.
-- =================================================================

CREATE OR REPLACE FUNCTION public.calcular_titulo(xp_total INT)
RETURNS VARCHAR AS $$
BEGIN
    IF xp_total >= 5000 THEN
        RETURN 'Apóstolo';
    ELSIF xp_total >= 2000 THEN
        RETURN 'Discípulo';
    ELSIF xp_total >= 500 THEN
        RETURN 'Aprendiz da Fé';
    ELSE
        RETURN 'Peregrino';
    END IF;
END;
$$ LANGUAGE plpgsql IMMUTABLE SET search_path = public, pg_temp;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, nome, email, xp)
    VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data->>'nome', 'Peregrino'),
        NEW.email,
        0
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

CREATE OR REPLACE FUNCTION public.handle_user_updated()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.email IS DISTINCT FROM OLD.email THEN
        UPDATE public.profiles
        SET email = NEW.email, updated_at = NOW()
        WHERE id = NEW.id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
    SELECT EXISTS (
        SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'
    );
$$ LANGUAGE sql SECURITY DEFINER STABLE SET search_path = public, pg_temp;

CREATE OR REPLACE FUNCTION public.conceder_conquista(p_user_id UUID, p_codigo VARCHAR)
RETURNS VOID AS $$
DECLARE
    v_conquista_id BIGINT;
BEGIN
    SELECT id INTO v_conquista_id FROM public.conquistas WHERE codigo = p_codigo;
    IF v_conquista_id IS NOT NULL THEN
        INSERT INTO public.usuario_conquistas (user_id, conquista_id)
        VALUES (p_user_id, v_conquista_id)
        ON CONFLICT (user_id, conquista_id) DO NOTHING;
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

-- IMPORTANTE: esta função é um helper INTERNO, chamado só de dentro de
-- outras funções SECURITY DEFINER (responder_pergunta, criar_liga,
-- entrar_liga, registrar_acesso). Ela aceita um p_user_id arbitrário e,
-- por padrão, o Postgres concede EXECUTE a qualquer role (PUBLIC) em
-- funções novas — o que permitiria a qualquer usuário autenticado chamar
-- supabase.rpc('conceder_conquista', { p_user_id: '<uuid de outra pessoa>' })
-- diretamente e forjar conquistas para si ou para terceiros. Revogamos o
-- EXECUTE público; as chamadas internas via PERFORM continuam funcionando
-- normalmente porque rodam no contexto do dono das funções chamadoras.
REVOKE EXECUTE ON FUNCTION public.conceder_conquista(UUID, VARCHAR) FROM PUBLIC;

CREATE OR REPLACE FUNCTION public.registrar_acesso()
RETURNS JSONB AS $$
DECLARE
    v_user_id UUID;
    v_hoje DATE := (timezone('utc'::text, now()))::date;
    v_ultimo DATE;
    v_atual INT;
    v_maior INT;
BEGIN
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Usuário não autenticado.';
    END IF;

    INSERT INTO public.streaks (user_id, streak_atual, maior_streak, ultimo_acesso)
    VALUES (v_user_id, 1, 1, v_hoje)
    ON CONFLICT (user_id) DO NOTHING;

    SELECT ultimo_acesso, streak_atual, maior_streak INTO v_ultimo, v_atual, v_maior
    FROM public.streaks WHERE user_id = v_user_id;

    IF v_ultimo = v_hoje THEN
        NULL;
    ELSIF v_ultimo = v_hoje - 1 THEN
        v_atual := v_atual + 1;
        v_maior := GREATEST(v_maior, v_atual);
        UPDATE public.streaks
        SET streak_atual = v_atual, maior_streak = v_maior, ultimo_acesso = v_hoje, updated_at = NOW()
        WHERE user_id = v_user_id;
    ELSE
        v_atual := 1;
        v_maior := GREATEST(v_maior, 1);
        UPDATE public.streaks
        SET streak_atual = 1, maior_streak = v_maior, ultimo_acesso = v_hoje, updated_at = NOW()
        WHERE user_id = v_user_id;
    END IF;

    IF v_atual >= 7 THEN
        PERFORM public.conceder_conquista(v_user_id, 'sequencia_7_dias');
    END IF;

    RETURN jsonb_build_object('streak_atual', v_atual, 'maior_streak', v_maior);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

-- responder_pergunta: adiciona "SET search_path" e passa a rejeitar
-- explicitamente perguntas desativadas ou de temporadas desativadas —
-- antes, só o filtro do frontend (.eq('ativa', true)) impedia isso, o que
-- não é proteção real (qualquer um pode chamar a RPC direto passando o id
-- de uma pergunta arquivada).
CREATE OR REPLACE FUNCTION public.responder_pergunta(
    p_pergunta_id BIGINT,
    p_resposta_selecionada CHAR(1)
)
RETURNS JSONB AS $$
DECLARE
    v_user_id UUID;
    v_resposta_correta CHAR(1);
    v_temporada_id BIGINT;
    v_pergunta_ativa BOOLEAN;
    v_temporada_ativa BOOLEAN;
    v_is_correct BOOLEAN := FALSE;
    v_ja_respondida BOOLEAN := FALSE;
    v_new_xp INT;
    v_new_nivel VARCHAR;
    v_total_perguntas INT;
    v_total_respondidas INT;
BEGIN
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Usuário não autenticado.';
    END IF;

    IF UPPER(p_resposta_selecionada) NOT IN ('A', 'B', 'C', 'D') THEN
        RAISE EXCEPTION 'Resposta inválida. Use A, B, C ou D.';
    END IF;

    SELECT p.resposta_correta, p.temporada_id, p.ativa, t.ativa
    INTO v_resposta_correta, v_temporada_id, v_pergunta_ativa, v_temporada_ativa
    FROM public.perguntas p
    JOIN public.temporadas t ON t.id = p.temporada_id
    WHERE p.id = p_pergunta_id;

    IF v_resposta_correta IS NULL THEN
        RAISE EXCEPTION 'Pergunta não encontrada.';
    END IF;

    IF NOT v_pergunta_ativa OR NOT v_temporada_ativa THEN
        RAISE EXCEPTION 'Esta pergunta não está mais disponível.';
    END IF;

    SELECT EXISTS (
        SELECT 1
        FROM public.respostas_usuario
        WHERE user_id = v_user_id
          AND pergunta_id = p_pergunta_id
    ) INTO v_ja_respondida;

    IF UPPER(v_resposta_correta) = UPPER(p_resposta_selecionada) THEN
        v_is_correct := TRUE;
    END IF;

    IF NOT v_ja_respondida THEN
        INSERT INTO public.respostas_usuario (user_id, pergunta_id, acertou)
        VALUES (v_user_id, p_pergunta_id, v_is_correct);

        IF v_is_correct THEN
            UPDATE public.profiles
            SET xp = xp + 100,
                updated_at = NOW()
            WHERE id = v_user_id
            RETURNING xp, nivel INTO v_new_xp, v_new_nivel;

            PERFORM public.conceder_conquista(v_user_id, 'primeira_resposta');

            SELECT COUNT(*) INTO v_total_perguntas
            FROM public.perguntas WHERE temporada_id = v_temporada_id AND ativa = true;

            SELECT COUNT(*) INTO v_total_respondidas
            FROM public.respostas_usuario ru
            JOIN public.perguntas p ON p.id = ru.pergunta_id
            WHERE ru.user_id = v_user_id AND p.temporada_id = v_temporada_id AND p.ativa = true;

            IF v_total_perguntas > 0 AND v_total_respondidas >= v_total_perguntas THEN
                PERFORM public.conceder_conquista(v_user_id, 'temporada_completa');
            END IF;
        ELSE
            SELECT xp, nivel INTO v_new_xp, v_new_nivel
            FROM public.profiles
            WHERE id = v_user_id;
        END IF;
    ELSE
        SELECT xp, nivel INTO v_new_xp, v_new_nivel
        FROM public.profiles
        WHERE id = v_user_id;
    END IF;

    RETURN jsonb_build_object(
        'correct', v_is_correct,
        'xp', v_new_xp,
        'nivel', v_new_nivel,
        'first_attempt', NOT v_ja_respondida
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

CREATE OR REPLACE FUNCTION public.criar_liga(p_nome TEXT)
RETURNS JSONB AS $$
DECLARE
    v_user_id UUID;
    v_codigo TEXT;
    v_nova_liga_id BIGINT;
    v_liga_nome VARCHAR;
    v_liga_codigo VARCHAR;
    v_ligas_criadas INT;
BEGIN
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Usuário não autenticado.';
    END IF;

    IF TRIM(p_nome) = '' THEN
        RAISE EXCEPTION 'Nome da liga não pode ser vazio.';
    END IF;

    IF LENGTH(TRIM(p_nome)) > 100 THEN
        RAISE EXCEPTION 'Nome da liga muito longo (máximo 100 caracteres).';
    END IF;

    SELECT COUNT(*) INTO v_ligas_criadas FROM public.ligas WHERE criado_por = v_user_id;
    IF v_ligas_criadas >= 3 THEN
        RAISE EXCEPTION 'Você já atingiu o limite de 3 ligas criadas por usuário.';
    END IF;

    v_codigo := UPPER(SUBSTRING(MD5(RANDOM()::TEXT || CLOCK_TIMESTAMP()::TEXT) FROM 1 FOR 8));

    INSERT INTO public.ligas (nome, codigo_acesso, criado_por)
    VALUES (TRIM(p_nome), v_codigo, v_user_id)
    RETURNING id, nome, codigo_acesso INTO v_nova_liga_id, v_liga_nome, v_liga_codigo;

    UPDATE public.profiles
    SET liga_id = v_nova_liga_id,
        updated_at = NOW()
    WHERE id = v_user_id;

    PERFORM public.conceder_conquista(v_user_id, 'fundador_liga');

    RETURN jsonb_build_object(
        'liga_id', v_nova_liga_id,
        'nome', v_liga_nome,
        'codigo_acesso', v_liga_codigo
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

CREATE OR REPLACE FUNCTION public.entrar_liga(p_codigo TEXT)
RETURNS JSONB AS $$
DECLARE
    v_user_id UUID;
    v_liga_id BIGINT;
    v_liga_nome VARCHAR;
    v_liga_codigo VARCHAR;
BEGIN
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Usuário não autenticado.';
    END IF;

    SELECT id, nome, codigo_acesso INTO v_liga_id, v_liga_nome, v_liga_codigo
    FROM public.ligas
    WHERE UPPER(codigo_acesso) = UPPER(TRIM(p_codigo));

    IF v_liga_id IS NULL THEN
        RAISE EXCEPTION 'Código de liga inválido ou não encontrado.';
    END IF;

    UPDATE public.profiles
    SET liga_id = v_liga_id,
        updated_at = NOW()
    WHERE id = v_user_id;

    PERFORM public.conceder_conquista(v_user_id, 'entrou_liga');

    RETURN jsonb_build_object(
        'liga_id', v_liga_id,
        'nome', v_liga_nome,
        'codigo_acesso', v_liga_codigo
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

CREATE OR REPLACE FUNCTION public.sair_liga()
RETURNS JSONB AS $$
DECLARE
    v_user_id UUID;
BEGIN
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Usuário não autenticado.';
    END IF;

    UPDATE public.profiles
    SET liga_id = NULL,
        updated_at = NOW()
    WHERE id = v_user_id;

    RETURN jsonb_build_object('success', true);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

-- Nova RPC: permite que o CRIADOR de uma liga recupere o código de acesso
-- para compartilhar de novo (ex: perdeu a mensagem original). Não expõe o
-- código a outros membros — ver seção 4 abaixo sobre por que a tabela
-- ligas deixa de expor essa coluna por SELECT direto.
CREATE OR REPLACE FUNCTION public.obter_minha_liga_codigo()
RETURNS JSONB AS $$
DECLARE
    v_user_id UUID;
    v_codigo VARCHAR;
BEGIN
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Usuário não autenticado.';
    END IF;

    SELECT l.codigo_acesso INTO v_codigo
    FROM public.ligas l
    JOIN public.profiles p ON p.liga_id = l.id
    WHERE p.id = v_user_id AND l.criado_por = v_user_id;

    IF v_codigo IS NULL THEN
        RETURN NULL;
    END IF;

    RETURN jsonb_build_object('codigo_acesso', v_codigo);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;


-- =================================================================
-- 2. PROFILES: RESTRINGE LEITURA AO PRÓPRIO DONO + VIEW DE RANKING
-- -----------------------------------------------------------------
-- A policy anterior ("Leitura de Profiles permitida para autenticados",
-- USING (true)) permitia que QUALQUER usuário autenticado lesse a tabela
-- profiles inteira — inclusive a coluna email de todo mundo — bastando
-- chamar supabase.from('profiles').select('*') pelo DevTools. O ranking
-- precisa mostrar nome/xp/nivel de outras pessoas, mas não precisa (e não
-- deve) expor e-mail. Solução: profiles fica restrito ao próprio dono, e
-- uma view separada expõe só as colunas seguras para todo mundo.
-- =================================================================
DROP POLICY IF EXISTS "Leitura de Profiles permitida para autenticados" ON public.profiles;
DROP POLICY IF EXISTS "Leitura do próprio Profile" ON public.profiles;
CREATE POLICY "Leitura do próprio Profile"
    ON public.profiles FOR SELECT
    TO authenticated USING (auth.uid() = id);

-- View pública de ranking: como é criada pelo role que roda esta migração
-- (tipicamente "postgres", que ignora RLS), ela consegue ler todas as
-- linhas de profiles mesmo com a policy acima restringindo ao próprio
-- dono — e reexpõe apenas as colunas não sensíveis.
CREATE OR REPLACE VIEW public.ranking_publico AS
SELECT id, nome, xp, nivel, liga_id
FROM public.profiles;

GRANT SELECT ON public.ranking_publico TO anon, authenticated;


-- =================================================================
-- 3. USUARIO_CONQUISTAS: RESTRINGE AO PRÓPRIO USUÁRIO
-- -----------------------------------------------------------------
-- Não há necessidade de produto comprovada para expor as conquistas de
-- outros usuários publicamente ainda, então fechamos por padrão. Se no
-- futuro quiser mostrar "medalhas" no ranking de liga, isso pode virar
-- outra view pública restrita a colunas específicas, como fizemos acima.
-- =================================================================
DROP POLICY IF EXISTS "Leitura de Conquistas de Usuários" ON public.usuario_conquistas;
CREATE POLICY "Leitura de Conquistas de Usuários"
    ON public.usuario_conquistas FOR SELECT
    TO authenticated USING (auth.uid() = user_id);


-- =================================================================
-- 4. LIGAS: ESCONDE codigo_acesso DA LEITURA DIRETA E TRAVA INSERT
-- -----------------------------------------------------------------
-- Antes, qualquer autenticado podia SELECT * FROM ligas e ver o
-- codigo_acesso de TODAS as ligas (o convite/senha de entrada), e também
-- podia fazer INSERT direto na tabela via PostgREST, contornando o limite
-- de 3 ligas por usuário que só existe dentro da RPC criar_liga.
-- =================================================================
REVOKE SELECT ON public.ligas FROM authenticated, anon;
GRANT SELECT (id, nome, criado_por, created_at) ON public.ligas TO authenticated;

REVOKE INSERT ON public.ligas FROM authenticated;
DROP POLICY IF EXISTS "Criação de Ligas permitida para autenticados" ON public.ligas;
-- (sem policy de INSERT para authenticated: toda criação de liga passa
-- exclusivamente pela RPC criar_liga, que roda como SECURITY DEFINER)


-- =================================================================
-- 5. CONSTRAINTS DE INTEGRIDADE
-- =================================================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'profiles_xp_nao_negativo') THEN
        ALTER TABLE public.profiles ADD CONSTRAINT profiles_xp_nao_negativo CHECK (xp >= 0);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'profiles_nome_nao_vazio') THEN
        ALTER TABLE public.profiles ADD CONSTRAINT profiles_nome_nao_vazio CHECK (LENGTH(TRIM(nome)) > 0);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ligas_nome_nao_vazio') THEN
        ALTER TABLE public.ligas ADD CONSTRAINT ligas_nome_nao_vazio CHECK (LENGTH(TRIM(nome)) > 0);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ligas_codigo_formato') THEN
        ALTER TABLE public.ligas ADD CONSTRAINT ligas_codigo_formato CHECK (codigo_acesso ~ '^[A-Z0-9]{6,10}$');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'perguntas_resposta_valida') THEN
        ALTER TABLE public.perguntas ADD CONSTRAINT perguntas_resposta_valida CHECK (resposta_correta IN ('A', 'B', 'C', 'D'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'perguntas_textos_nao_vazios') THEN
        ALTER TABLE public.perguntas ADD CONSTRAINT perguntas_textos_nao_vazios CHECK (
            LENGTH(TRIM(texto_pergunta)) > 0 AND
            LENGTH(TRIM(opcao_a)) > 0 AND LENGTH(TRIM(opcao_b)) > 0 AND
            LENGTH(TRIM(opcao_c)) > 0 AND LENGTH(TRIM(opcao_d)) > 0
        );
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'temporadas_titulo_nao_vazio') THEN
        ALTER TABLE public.temporadas ADD CONSTRAINT temporadas_titulo_nao_vazio CHECK (LENGTH(TRIM(titulo)) > 0);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'temporadas_ordem_nao_negativa') THEN
        ALTER TABLE public.temporadas ADD CONSTRAINT temporadas_ordem_nao_negativa CHECK (ordem IS NULL OR ordem >= 0);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'perguntas_ordem_nao_negativa') THEN
        ALTER TABLE public.perguntas ADD CONSTRAINT perguntas_ordem_nao_negativa CHECK (ordem IS NULL OR ordem >= 0);
    END IF;
END $$;

-- NOTA sobre "uma única temporada ativa": decidimos NÃO forçar essa regra
-- no banco, porque é uma decisão de produto, não uma invariante técnica —
-- pode fazer sentido rodar duas temporadas em paralelo (ex: "Advento" e
-- "Vidas de Santos" ao mesmo tempo). Se um dia isso virar regra de
-- negócio obrigatória, um índice único parcial resolve:
--   CREATE UNIQUE INDEX temporadas_unica_ativa ON public.temporadas ((true)) WHERE ativa;
-- (garante no máximo 1 linha com ativa = true no banco inteiro).

-- NOTA sobre "impedir múltiplas ligas simultâneas por usuário": já é
-- garantido pelo modelo de dados — profiles.liga_id é uma FK única por
-- linha (um usuário só pode apontar para uma liga por vez), não uma
-- tabela de associação N:N.


-- =================================================================
-- 6. TABELA DE AUDITORIA ADMINISTRATIVA
-- -----------------------------------------------------------------
-- Loga automaticamente (via trigger) toda alteração em temporadas,
-- perguntas e mudanças de role em profiles — não depende de nenhuma tela
-- específica do admin lembrar de chamar uma função de log.
-- =================================================================
CREATE TABLE IF NOT EXISTS public.auditoria_admin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    acao VARCHAR(20) NOT NULL,
    entidade VARCHAR(50) NOT NULL,
    entidade_id TEXT,
    valores_antigos JSONB,
    valores_novos JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_auditoria_admin_created_at ON public.auditoria_admin(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_auditoria_admin_entidade ON public.auditoria_admin(entidade, entidade_id);

ALTER TABLE public.auditoria_admin ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Somente admin lê auditoria" ON public.auditoria_admin;
CREATE POLICY "Somente admin lê auditoria"
    ON public.auditoria_admin FOR SELECT
    TO authenticated USING (public.is_admin());

GRANT SELECT ON public.auditoria_admin TO authenticated;
-- Sem GRANT de INSERT/UPDATE/DELETE para authenticated: só a trigger
-- abaixo (rodando como SECURITY DEFINER, dono postgres) grava aqui.

CREATE OR REPLACE FUNCTION public.registrar_auditoria()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.auditoria_admin (admin_id, acao, entidade, entidade_id, valores_antigos, valores_novos)
    VALUES (
        auth.uid(),
        TG_OP,
        TG_TABLE_NAME,
        COALESCE(NEW.id::TEXT, OLD.id::TEXT),
        CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN to_jsonb(OLD) ELSE NULL END,
        CASE WHEN TG_OP IN ('UPDATE', 'INSERT') THEN to_jsonb(NEW) ELSE NULL END
    );
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

DROP TRIGGER IF EXISTS audit_temporadas ON public.temporadas;
CREATE TRIGGER audit_temporadas
    AFTER INSERT OR UPDATE OR DELETE ON public.temporadas
    FOR EACH ROW EXECUTE FUNCTION public.registrar_auditoria();

DROP TRIGGER IF EXISTS audit_perguntas ON public.perguntas;
CREATE TRIGGER audit_perguntas
    AFTER INSERT OR UPDATE OR DELETE ON public.perguntas
    FOR EACH ROW EXECUTE FUNCTION public.registrar_auditoria();

DROP TRIGGER IF EXISTS audit_profiles_role ON public.profiles;
CREATE TRIGGER audit_profiles_role
    AFTER UPDATE OF role ON public.profiles
    FOR EACH ROW
    WHEN (OLD.role IS DISTINCT FROM NEW.role)
    EXECUTE FUNCTION public.registrar_auditoria();


-- =================================================================
-- 7. REMOVE OS DEFAULT PRIVILEGES EXCESSIVAMENTE PERMISSIVOS
-- -----------------------------------------------------------------
-- O script original fazia toda tabela FUTURA herdar automaticamente
-- SELECT/INSERT/UPDATE/DELETE para "authenticated" e SELECT para "anon",
-- independente de RLS estar correta para ela. Revertendo isso força que
-- toda tabela nova passe por uma decisão explícita de GRANT, como as que
-- fizemos aqui para streaks/conquistas/auditoria_admin.
-- =================================================================
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE SELECT ON TABLES FROM anon;

-- =================================================================
-- FIM DA ATUALIZAÇÃO 2
-- -----------------------------------------------------------------
-- Checklist pós-deploy recomendado:
--   1. Confirme que o front busca ranking em `ranking_publico`, não em
--      `profiles` diretamente (já ajustado no patch do frontend).
--   2. Confirme que nenhuma tela faz `.from('ligas').select('*')` — use
--      apenas colunas explícitas (id, nome), já que codigo_acesso não é
--      mais legível diretamente.
--   3. Rode como um usuário comum: `select * from profiles;` deve
--      retornar só a própria linha. `select * from ligas;` deve dar erro
--      de coluna/permissão ao tentar pegar codigo_acesso.
-- =================================================================